### PR TITLE
Add database backend support for CockroachDB

### PR DESCRIPTION
**Pull request by d4l3k**
This is WIP support for CockroachDB.

Tracking issue #740

Please let me know if there's anything I can do to make this mesh better with the existing code base. I'm not particularly familiar with how gorm is structured, and it's rather unconventional.

Thanks!

### CODE REVIEW

**Comment by d4l3k** [comment]
Looks like the wrecker/golang box needs to update GCC to support `-std=c++11`.

**Comment by jinzhu** [comment]
Hi @d4l3k 

Thank you for this, but I am working on the v1.0 release, the API would be changed, so could you wait a little bit and then work on that based on v1.0_dev branch? Will notice you when it is ready.

**Comment by d4l3k** [comment]
Sure thing. Thanks for your hard work!

**Comment by jinzhu** [comment]
Cool, thank you ;)

**Comment by joeblew99** [comment]
I am using Gorm with Gorma.

I am wanting to use cockroach DB, rather than postreSQL.

Could someone give their opinion about how well GORM and CockroachDB are working togther these days.
I was using the postresql driver for cockroachdb, but i am really hoping that GORM support is now good enough.

**Comment by joeblew99** [comment]
@d4l3k 

Hey Tristian,

https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go

Looks like things have gotten easier to use.
Can you let me know how you are finding using GORM and Cockroach please ?
I am eager to dive in.

**Comment by d4l3k** [comment]
I don't believe that Gorm actually supports cockroach in any way yet (other than through the Postgres driver).

CockroachDB currently doesn't support joins which makes it kind of hard to use it as a backend for gorm. I'll probably try to update this PR so it can actually be merged.

**Comment by joeblew99** [comment]
I realised the lack of joins too, after I posted the issue.

So it's still to wait I think.

**Comment by koalalorenzo** [comment]
Any update to support CockroachDB? 😖 Are we still waiting?

**Comment by d4l3k** [comment]
I believe it CockroachDB works without any issues now.

**Comment by koalalorenzo** [comment]
it doesn't :( https://github.com/cockroachdb/cockroach/issues/24838

**Comment by d4l3k** [comment]
Huh, think that's probably a regression. I could have sworn I built a project on top of Gorm and CDB.

**Comment by koalalorenzo** [comment]
Do you remember the version you were using? maybe that old version works :(

**Pull request closed without merging**
