### PR TITLE
corresponds timestamp precision for mysql

### PR DESCRIPTION
**Pull request by miya-masa**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested
- [x] Write good commit message, try to squash your commits into a single one
- [x] Run `./build.sh` in `gh-pages` branch for document changes

For significant changes like big bug fixes, new features, please open an issue to make a agreement on an implementation design/plan first before starting it.

Thank you.

### What did this pull request do?
corresponds timestamp precision for mysql

### CODE REVIEW

**Comment by ozkar99** [comment]
An alternative is adding `gorm:"type:timestamp(6)"` (or the precision you want)  to your timestamps on the struct annotations.

**Comment by miya-masa** [comment]
If precision is specified, sqlite or postgres will not be timestamp type.
Only mysql needs precision.

**Comment by TwistedHardware** [comment]
Can you also add a default size in case the size tag was not passed. This can some in handy when you are dealing with `UpdatedAt` from `gorm.Model` where you don't really have cannot really edit that tag. I good default size would be 6 because it is the largest possible precision. By default in SQLite, you will get precision of 9 to match the nano second precision of Golang time.

**Comment by jinzhu** [comment]
Merged, but you need to use tag `precision` to set timestamp's precision

**Pull request closed without merging**
