### PR TITLE
Do not always override select on pluck

### PR DESCRIPTION
**Pull request by matematik7**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested
- [x] Write good commit message, try to squash your commits into a single one
- [x] Run `./build.sh` in `gh-pages` branch for document changes

For significant changes like big bug fixes, new features, please open an issue to make a agreement on an implementation design/plan first before starting it.

Thank you.

### What did this pull request do?

I want to run query like this:
`DB.Model(&Entry).Select("date_part('year', created_at) as year").Pluck("year", &years)`
The select statement was getting overriden by pluck.

### CODE REVIEW

**Comment by jinzhu** [comment]
it will broken if the `as` is quoted like below?

```go
DB.Model(&Entry).Select("date_part('year', created_at) as \"year\"").Pluck("year", &years)
```

**Comment by matematik7** [comment]
@jinzhu you are right, I've fixed that and also added the test.

**Comment by matematik7** [comment]
Will this pull request ever be merged? Anything I still have to fix?

**Comment by jinzhu** [comment]
Merged this PR, thank you for your work.

**Pull request closed without merging**
