### PR TITLE
Fixed issue https://github.com/jinzhu/gorm/issues/151 where postgresql connection problems fail silently

### PR DESCRIPTION
**Pull request by pariz**
For reference: https://github.com/jinzhu/gorm/issues/151
Errors connection to a postgresql fail silently, resulting in errors. This fix sends a ping right after the connection has been made. If the ping fails, we assume the connection is broken.

Accepting better solutions. This quick fix did it for me :)

### CODE REVIEW

**Comment by jinzhu** [comment]
Should we always `Ping()` the database after connection?

**Comment by pariz** [comment]
It's not the most pretty solution. But it an extra safetycheck to verify that the connection is in fact alive.

**Comment by pariz** [comment]
Should i rewrite the pr and make the `Ping()` generic?

**Comment by jinzhu** [comment]
Hi @pariz 

Yes, I think it is a better solution than just check the postgres.

**Comment by pariz** [comment]
I agree. Code has been updated. Epic oneliner! :)

**Comment by jinzhu** [comment]
picked your code to the master, thank you.

**Pull request closed without merging**
