### PR TITLE
Mysql foreign key length fix

### PR DESCRIPTION
**Pull request by nkovacs**
This is based on #947, but it doesn't add a new method, it automatically hashes the key name if it would be too long on mysql.
I had to add a new method to Dialect to make the foreign key name different for mysql.

### CODE REVIEW

**Comment by jinzhu** [comment]
That looks much better, thank you for the PR.

**Comment by benguild** [comment]
Thanks!!

**Comment by nkovacs** [comment]
There's a panic if dest is shorter than 24 bytes, I'll fix it soon (as well as the string length calculation, because it should count utf8 characters, not bytes).

**Comment by cristian-sima** [comment]
Happy #947 is done :100: Tx @nkovacs for supporting this

**Pull request merged**
