### PR TITLE
add tag ForeignColumn and AssociationForeignColumn

### PR DESCRIPTION
**Pull request by xujinzheng**
add tag ForeignColumn and AssociationForeignColumn for because of anonymous have no name of type

由于匿名结构体或使用反射方法`reflect.SturctOf`生成出来的结构体无法获取类型名称，因此需要加入标签来解决关联问题

### CODE REVIEW

**Comment by xujinzheng** [comment]
if we do not add  `AssociationForeignColumn` and  `ForeignColumn` tags, the `Languages` will be nil

如下用法如果不加入 `AssociationForeignColumn` 和 `ForeignColumn` 两个Tag是无法查询到 `Languages` 的

```go
user := User{}

u := db.Find(&user, "id = ?", 2)

u.Association("BillingAddress").Find(&user.BillingAddress)
u.Association("ShippingAddress").Find(&user.ShippingAddress)
u.Association("Emails").Find(&user.Emails)
u.Association("Languages").Find(&user.Languages)
```

```go
type Table struct {
}

func (p Table) TableName() string {
	return "languages"
}

type User struct {
	gorm.Model
	Birthday *time.Time
	Age      int
	Name     string `gorm:"size:255"` // Default size for string is 255, reset it with this tag
	Num      int    `gorm:"AUTO_INCREMENT"`

	CreditCard CreditCard // One-To-One relationship (has one - use CreditCard's UserID as foreign key)
	Emails     []Email    // One-To-Many relationship (has many - use Email's UserID as foreign key)

	BillingAddress   Address // One-To-One relationship (belongs to - use BillingAddressID as foreign key)
	BillingAddressID sql.NullInt64

	ShippingAddress   Address // One-To-One relationship (belongs to - use ShippingAddressID as foreign key)
	ShippingAddressID int

	IgnoreMe int `gorm:"-"` // Ignore this field
	// Languages []Language `gorm:"many2many:user_languages;"` // Many-To-Many relationship, 'user_languages' is join table

	Languages []struct {
		Table
		ID   int    `gorm:"primary_key;AssociationForeignColumn:LanguageID"`
		Name string `gorm:"index:idx_name_code;"` // Create index with name, and will create combined index if find other fields defined same name
		Code string `gorm:"index:idx_name_code"`  // `unique_index` also works
	} `gorm:"many2many:user_languages;ForeignColumn:UserID"`
}
```

**Comment by jinzhu** [comment]
Hello @xujinzheng

Could you add a test to break current codebase, and fix that with your changes?

**Comment by xujinzheng** [comment]
I will do it latter.

**Comment by jinzhu** [comment]
Hi @xujinzheng 

I think this issue should be resolved with tag `association_foreignkey`, `association_jointable_foreignkey`. refer: http://gorm.io/associations.html#self-referencing-many-to-many-relationship

Thank you for your PR.

**Pull request closed without merging**
