### PR TITLE
sqlite not support comment

### PR DESCRIPTION
**Pull request by duguying**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested

For significant changes like big bug fixes, new features, please open an issue to make an agreement on an implementation design/plan first before starting it.

### What did this pull request do?

in sqlite3, migrate sql clause does not support field comment, if dialect is sqlite3, do not parse `COMMENT`

### CODE REVIEW

**Comment by zaneli** [comment]
Should you implement in [dialects/sqlite/sqlite.go](https://github.com/jinzhu/gorm/blob/33ef36532db4ad1db9eb6e786261e9db5984de31/dialects/sqlite/sqlite.go)?

**Comment by duguying** [comment]
@zaneli This is the smallest change.

**Comment by duguying** [comment]
@zaneli 能合并么？因为我写单元测试的时候会用到sqlite，遇到comment报错。相信sqlite写单元测试的人都会遇到这个问题。

**Comment by jinzhu** [comment]
thank you for your PR, so not going to merge any PR because it will introduce lots of conflictions when releasing v2, sorry.

**Comment by aveyuan** [comment]
Good PR,Sqlite should auto cacel Comment.

**Pull request closed without merging**
