### PR TITLE
Implementatoin of possibility to reconnect

### PR DESCRIPTION
**Pull request by ruslanfedoseenko**
Make sure these boxes checked before submitting your pull request.

- [*] Do only one thing
- [] No API-breaking changes
- [] New code/logic commented & tested
- [*] Write good commit message, try to squash your commits into a single one
- [] Run `./build.sh` in `gh-pages` branch for document changes

For significant changes like big bug fixes, new features, please open an issue to make a agreement on an implementation design/plan first before starting it.

Thank you.

### What did this pull request do?
Implement possibility to reconnect in case of failture.
Currently dont have any time to test it - will do it later.

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @ruslanfedoseenko 

I have merged it to branch `ruslanfedoseenko-master`, and refactored it as plugins

please check it out.

https://github.com/jinzhu/gorm/tree/ruslanfedoseenko-master/plugins/reconnect

Let me know if you found any problems.

**Comment by ruslanfedoseenko** [comment]
Problem I see that you need to block execution of any SQL if one thread failed. Thats why I created a WaitGroup and use it in all default call backs.  I use wait group as it allows concurent execution of normal sql in case there is now error. I f you use mutex it will blocck acces to db during 1 query.
Why you need to block execution of sql during reconnect:
Lets imagine situation - 3 Thread all failed. All thread starts reconnect and due to mutex only one will create new connection after that another  will create new connection etc.

So I think it may be done with anther before callback 

Also It is possible that one thread already starts reconnect and another just finished executeion of sql and detectred that it need reconnect

**Comment by jinzhu** [comment]
>  3 Thread all failed. All thread starts reconnect and due to mutex only one will create new connection after that another will create new connection etc

No, this won't happen, if you noticed this line `connected := db.DB().Ping() == nil` after the lock, it will check current db is alive or not, and won't reconnect db if it is already connected.

> Also It is possible that one thread already starts reconnect and another just finished executeion of sql and detectred that it need reconnect

Yes, I understand, so there is a TODO left, it will rerun all failed SQL due to the bad connection issue... I will look into it later.

**Comment by jinzhu** [comment]
Not going to merge it, will move it as a GORM plugin

**Pull request closed without merging**
