### PR TITLE
go modules

### PR DESCRIPTION
**Pull request by istsh**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested

For significant changes like big bug fixes, new features, please open an issue to make an agreement on an implementation design/plan first before starting it.

### What did this pull request do?
corresponded to go modules

### CODE REVIEW

**Comment by konradreiche** [comment]
Without this change it seems gorm cannot easily be added using Go Modules.

**Comment by inliquid** [comment]
GORM works with modules just fine, without this change.

**Comment by jonathaningram** [comment]
@jinzhu it looks like the module import path you committed is not `jinzhu` rather it's `istsh`? Was that intentional?

See https://github.com/jinzhu/gorm/blob/4b13e079fcea637fcb166ee1752c8d80601e3ef0/go.mod#L1

```
module github.com/istsh/gorm
```

Also, the go.mod and go.sum in my PR #2307 was generated automatically by Go and so it includes quite a lot more than what you merged into master. Is there any reason for only including `github.com/jinzhu/inflection` in `go.mod`?

cc @istsh

**Comment by inliquid** [comment]
That's mistake. Please revert this commit @jinzhu

**Pull request merged**
