### PR TITLE
[WIP] Integrated tidb dialect

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
```
# GORM_DIALECT=tidb go test ./...
# github.com/pingcap/tidb/parser
../../pingcap/tidb/parser/lexer.go:81: undefined: yySymType
../../pingcap/tidb/parser/misc.go:474: undefined: yySymType
../../pingcap/tidb/parser/yy_parser.go:73: undefined: yySymType
../../pingcap/tidb/parser/yy_parser.go:74: undefined: yySymType
../../pingcap/tidb/parser/yy_parser.go:75: undefined: yySymType
testing tidb...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x421b81a]

goroutine 1 [running]:
panic(0x45b8d20, 0xc82000a140)
       	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
database/sql.(*DB).SetMaxIdleConns(0x0, 0xa)
       	/usr/local/Cellar/go/1.6/libexec/src/database/sql/sql.go:568 +0x1aa
github.com/jinzhu/gorm_test.OpenTestConnection(0xc820101220, 0x4ead028, 0xc8200da650)
       	/Users/thomas/Developer/golang/src/github.com/jinzhu/gorm/main_test.go:77 +0x4ab
github.com/jinzhu/gorm_test.init.1()
       	/Users/thomas/Developer/golang/src/github.com/jinzhu/gorm/main_test.go:31 +0x30
github.com/jinzhu/gorm_test.init()
       	/Users/thomas/Developer/golang/src/github.com/jinzhu/gorm/utils_test.go:30 +0x94
main.init()
       	github.com/jinzhu/gorm/_test/_testmain.go:336 +0x4f
FAIL   	github.com/jinzhu/gorm 	0.023s
?      	github.com/jinzhu/gorm/dialects/mssql  	[no test files]
?      	github.com/jinzhu/gorm/dialects/mysql  	[no test files]
?      	github.com/jinzhu/gorm/dialects/postgres       	[no test files]
?      	github.com/jinzhu/gorm/dialects/sqlite 	[no test files]
```

Sadly it seems to be broken somehow :(

**Comment by ThreeBearsDan** [comment]
Tidb doesn't have driver right now. Certainly, u can look tidb as mysql. so u can use mysql driver to connect tidb. So there's no need to add tidb. just think tidb is a mysql server.

**Comment by tboerger** [comment]
That's simply not entirely true, you can use tidb also as an integrated database based on files, comparable with sqlite.

**Comment by tboerger** [comment]
I won't waste my time on that anymore. Doesn't look like there is any big interest in that at all.

**Comment by jinzhu** [comment]
Hi @tboerger 

This is not doable unless tidb provides a sqlite like dialect github.com/mattn/go-sqlite3 for its integrated db.

Rightnow, you can only use its mysql protocol.

**Comment by tboerger** [comment]
That's not true. XORM integrates tidb without the mysql protocol. There you can use tidb as an embedded database, https://github.com/go-gitea/gitea integrates that based on the `tidb` build flag.

**Comment by tboerger** [comment]
The XORM integration is done within https://github.com/go-xorm/tidb

**Comment by jinzhu** [comment]
Trying to check out tidb, but failed to install it...

image

Will check it again when it becomes more stable.

**Comment by iu0v1** [comment]
@jinzhu, look like it's [ok](https://github.com/pingcap/tidb/issues/2483) :)

**Comment by tboerger** [comment]
The second error is because tidb requires a make invoke.

**Comment by jinzhu** [comment]
I have tried

```sh
git clone https://github.com/pingcap/tidb.git $GOPATH/src/github.com/pingcap/tidb
cd $GOPATH/src/github.com/pingcap/tidb
make
```

then run this go script

```go
package main

import (
        "database/sql"
        "fmt"

        _ "github.com/pingcap/tidb"
)

func main() {
        db, err := sql.Open("tidb", "memory://tidb/tidb")
        fmt.Println(err)
        fmt.Println(db.Ping())
}
```

Got this error 
image

**Pull request closed without merging**
