### PR TITLE
Add new tag "not_auto_increment" to set a column can auto increase or…

### PR DESCRIPTION
**Pull request by WingGao**
Example

```go
type CourseHourResource struct {
	Type                           uint32 `gorm:"type:tinyint"`
	CourseHourID            uint32 `gorm:"primary_key"`
	CourseChapterResourceID uint32 `gorm:"primary_key;not_auto_increment"`
}
```
Result
```sql
CREATE TABLE `px_course_hour_resource` (`type` tinyint,`course_hour_id` int unsigned AUTO_INCREMENT,`course_chapter_resource_id` int unsigned , PRIMARY KEY (`course_hour_id`,`course_chapter_resource_id`))   
```

Fix
https://github.com/jinzhu/gorm/issues/1595
https://github.com/jinzhu/gorm/issues/1585
https://github.com/jinzhu/gorm/issues/1568
https://github.com/jinzhu/gorm/issues/1527

### CODE REVIEW

**Comment by rookie7799** [comment]
Any updates on this ?

**Comment by philipyao** [comment]
tag "not_auto_increment" still does NOT work for single primary_key. @WingGao

**Comment by jinzhu** [comment]
Merged, but changed to you set `gorm:"primary_key;auto_increment:false"` to mark a column not auto increaseable

Thank you for your PR.

**Comment by lianhongHou** [comment]
Why does it not work for me? I use mysql driver.

**Comment by echobool** [comment]
找得我好辛苦啊，能不能写在文档里啊 大哥

**Comment by winyh** [comment]
这问题是真坑，强烈建议写文档里，我mark一下...找的好辛苦

**Pull request closed without merging**
