### PR TITLE
fix can't get some filed

### PR DESCRIPTION
**Pull request by oiooj**
fix can't get some fileds

### CODE REVIEW

**Comment by oiooj** [comment]
@jinzhu review plz

**Comment by jinzhu** [comment]
Hello @oiooj 

What did this pull request fix, could you add a test case for this?

**Comment by oiooj** [comment]
@jinzhu  , I sent you an email

**Comment by oiooj** [comment]
@jinzhu  , when field.IsIgnored is true?

**Comment by jinzhu** [comment]
When using tag `sql:"-"`

**Pull request closed without merging**
