### PR TITLE
add JSONB type

### PR DESCRIPTION
**Pull request by Aetheus**
### What did this pull request do?
Add a JSONB type to the postgres dialect. I'm aware of @Niondir raising an issue for this (https://github.com/jinzhu/gorm/issues/1183), but it's been nearly a year since then and as I don't see any current PRs for this so I have decided to go ahead and make a PR for it so future users of the ORM won't have to constantly reinvent this struct.

### CODE REVIEW

**Comment by Aetheus** [comment]
Not entirely certain why codeclimate is failing this PR on the very first line of postgres.go ("package postgres"), as this line was unmodified, and seems perfectly legal anyway considering that its the intended package name. 

The failed check has no description either, so I'm not entirely sure what needs to be modified to pass the check. Any possible advice, @jinzhu ?

**Comment by jvoorhis** [comment]
+1

I cannot reproduce the codeclimate warning with the latest tools.

```
$ go fmt  // no output
$ echo $?
0
$ go version
go version go1.9 linux/amd64
```

**Comment by jinzhu** [comment]
thank you for your PR

**Comment by SongCF** [comment]
How do I use it?Can you give me an example?

**Comment by Aetheus** [comment]
I saw a comment here earlier asking about how to use this. It looks like it's since been deleted, but for other folks who might be curious:


Assuming you have a "documents" table, and in that documents you have a "metadata" jsonb column, your resulting model struct definition may look something like this:

````
package yourPackageName

import (
	"time"
	"github.com/jinzhu/gorm/dialects/postgres"
)

type Document struct {
	Metadata postgres.Jsonb		`json:"requirements"`
	Body string				        `json:"body"`

	//housekeeping attributes
	ID        int					        `json:"id"`
	CreatedAt time.Time			`json:"created_at"`
	UpdatedAt time.Time			`json:"updated_at"`
}

````

Assuming you wanted to access the value of "Metadata" in a specific "Document" as a string ... 

````
func GetMetadataOfDocument(dbConn *gorm.DB, documentId int) string {
    doc := Document{}
    dbConn.Where("id = ?", documentId).First(&doc)

    stringVal := string(doc.Metadata.RawMessage)
    return stringVal;
}
````

**Comment by januszm** [comment]
@Aetheus thanks for this, but it seems that you have to manually convert the `Metadata` from bytes to string. What if you simply want to use that `Jsonb` column in the API response built with `json.NewEncoder(w).Encode(result)`  (where, let's say that `result` contains the `Document` from your example).

In the above case what I see in the response is the array of bytes `[123 34 56 ...]` and I'd like to have them converted to string somehow.

**Pull request merged**
