### PR TITLE
Add gorm.Gormw, an interface wrapper for gorm.DB

### LINKED ISSUE #729: Make the DB an interface for easier testing?
It will be great if the DB type can be turned into an interface, so users can mock the interface in tests as appropriate. Otherwise we will need to do wrappers etc. to achieve this, which isn't optimal.

Were there any reasons why it started as a struct?

Thanks!

### PR DESCRIPTION
**Pull request by littledot**
Fixes #729. This PR adds an interface-equivalent of gorm.DB so that those who prefer mocking gorm.DB under test can easily do so. It also adds 2 functions Wrap() and Openw(), to facilitate creating gorm.Gormw instances.

This PR aims to achieve the same results as #805 by introducing a gorm.DB wrapper interface instead of making changes to gorm.DB. It introduces less code changes and ensures backwards-compatibility.

Unit tests are basic because I'd like to know your thoughts first.

### CODE REVIEW

**Comment by Azuka** [comment]
This looks really great. @jinzhu do you think we'll be getting this in any time soon?

**Comment by Selvatico** [comment]
Hello guys, please check my own bicycle which we use with **gorm** to mock for tests https://github.com/Selvatico/go-mocket . Maybe it could be useful too.

**Comment by AgrimPrasad** [comment]
@jinzhu This will be very helpful indeed for writing unit tests... Any plans on getting this in soon?

**Comment by jinzhu** [comment]
I think this is not necessary to be merged into GORM, you could extract those code and make a wrapper for gorm?

Thank you for your work.

**Comment by kacperjurak** [comment]
Hi,

I took @littledot code and create an external package with this interface and wrapper - https://github.com/kacperjurak/igorm. All credit goes to @littledot.

**Pull request closed without merging**
