### PR TITLE
concurrent preloads

### PR DESCRIPTION
**Pull request by jlburkhead**
turning https://github.com/jinzhu/gorm/issues/1083 into a pr

### CODE REVIEW

**Comment by jinzhu** [comment]
Seems CI failed.

**Comment by jlburkhead** [comment]
@jinzhu If you're open to adding this I can spend time to figure out why the tests are failing. Seems like it will take some time to figure out since each test passes individually, but running all of them fails certain checks

**Comment by jinzhu** [comment]
Hi @jlburkhead 

Yes, good to have that if it does improved the performance.

**Comment by Fyb3roptik** [comment]
Is this something that would fix #1436 ????

**Comment by zardak** [comment]
@Fyb3roptik Its about running multiple preload queries in parallel rathen than sequentially. This has nothing to do with tweaking the preload strategy.

**Comment by canhlinh** [comment]
I will check this ticket.

**Comment by canhlinh** [comment]
Hmm. The code can not work in concurrent.
```
In each goroutine, the result update result to scope. It causes the error. 
Need to refactor the code to implement concurrent.
```

**Comment by lunemec** [comment]
Please also be very careful when running inside transaction. That will mean all of those goroutines will share 1 TCP connection to the DB (something to consider and test for).

**Comment by jinzhu** [comment]
No feedback for a long while, going to close it for now.

**Pull request closed without merging**
