### PR TITLE
fix raw with soft delete

### LINKED ISSUE #1468: db.RAW() doesn't work with soft deletion
yes

### PR DESCRIPTION
**Pull request by azhao12345**
fixes #1468

Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested
- [x] Write good commit message, try to squash your commits into a single one
- [x] Run `./build.sh` in `gh-pages` branch for document changes

For significant changes like big bug fixes, new features, please open an issue to make a agreement on an implementation design/plan first before starting it.

Thank you.

### CODE REVIEW

**Comment by jinzhu** [comment]
this is an expected behaviour

**Comment by azhao12345** [comment]
no its not.. i doesnt work at all

**Comment by jinzhu** [comment]
`Raw` will ignore `SoftDelete` conditions is an expected behaviour

**Comment by azhao12345** [comment]
it doesn't ignore the condition.  It crashes the program

**Pull request closed without merging**
