### PR TITLE
Database interface for easy mocking gorm

### PR DESCRIPTION
**Pull request by alvarowolfx**
Still WIP but I opened the PR just to show what I tried to explain on #729. You can see in the example folder a use case of the interface based testing. 

I made a mistake of developing on master branch, later I will change and merge with the branch v1.0_dev for better integration. 

Please @jinzhu let me know your opinion on this.

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @alvarowolfx 

Thank you for your pull request.

But from those changes, I think I am not a fan of mock testing, don't would like to increase GORM's complexity for that.

It might always good to use real database for testing, or let me know if you have any problems of that, to see I could help on it.

**Comment by alvarowolfx** [comment]
What complexity are you talking about @jinzhu ?! Just changed some method name and the mocks package was autogenerated. As I sais still WIP and can be enhanced.

If you can give me a example of testing the same method that I wrote on the example folder, without mocks, I will like and thanks.

**Comment by jinzhu** [comment]
@alvarowolfx what the problem of testing it with real data in real database?

**Comment by alvarowolfx** [comment]
@jinzhu I don't know a way to test the example that I wrote without re-testing gorm itself, that why I asked for a example on how would do it. 

Testing with the database also makes the tests to run more slowly. And this article talks more about mocks : http://martinfowler.com/articles/mocksArentStubs.html 

I'm not trying to complicate things, just trying to apply technics already used in other languages to facilitate testing. Your work on gorm is awesome, i'm not trying to break this.

**Comment by jinzhu** [comment]
I understand, and I have tried mock testing when using Ruby, but finally dropped it, think it doesn't really provide us any value, more time costing, and even get more bugs.

My understanding, unit tests is testing get this results with those inputs, I don't really care how it works, so I don't think you are re-testing GORM, when you writes those tests, you don't even need to know it is written with GORM or not. You are just testing it works like you want or not.

And seems like Martin Fowler also not a fan of this, also refer: https://www.thoughtworks.com/insights/blog/mockists-are-dead-long-live-classicists

**Comment by ryanwalls** [comment]
@alvarowolfx Thanks for your effort on this.  I would have loved to see this merged.  Using interfaces to define complex operations is idiomatic go in my opinion.  Would have made unit testing our code much much easier.

**Comment by RichardKnop** [comment]
I prefer functional tests. Just create a test database and run tests against it.

You would be surprised how many small edge case issues get caught when using real database in tests over the years.

I am a big fan of unit tests but when testing something like REST API I prefer functional tests ala Django/RoR.

**Comment by ryanwalls** [comment]
@RichardKnop Agree on functional tests being important, but testing error cases would be easier with mocking.  I am encapsulating gorm interactions with a service class like you suggested.  The missing piece is a real unit test that verifies that I'm doing error handling correctly.  

e.g. 
Wrapping function:
```
func (s *service) CreateOrganization(organization *models.Organization) error {
	return s.db.Create(organization).Error
}
```  
No easy way to unit test that I am returning the error from this function.  But I can live with it because it's not a very complex method... but being a TDD aficionado, I get just a little sad.  ;)

**Comment by littledot** [comment]
@alvarowolfx @jinzhu Putting testing ideologies aside, could we achieve the same results with a delegate wrapper? Seems like less code and also guarantees backwards-compatibility.

For example:
```go
package gormw
...

type DB interface {
        Create(value interface{}) DB
}

// Wrap wraps gorm.DB in an interface
func Wrap(db *gorm.DB) DB {
	return &gormw{db}
}

type gormw struct {
	w *gorm.DB
}

func (it *gormw) Create(value interface{}) DB {
	return Wrap(it.w.Create(value))
}

```

**Comment by RichardKnop** [comment]
@ryanwalls Actually you can unit test with the service class you are using, just define an interface:

```go
interface ServiceInterface {
    CreateOrganization(organization *models.Organization) error
}
```

Then use [mockery](https://github.com/vektra/mockery) to create a mock struct defined by that interface. And use that in unit tests, you can mock what the service returns (errors for example) using the mock struct and something like [testify](https://github.com/stretchr/testify).

**Comment by ryanwalls** [comment]
@RichardKnop Yep, that's what I do.  But you still aren't verifying that `CreateOrganization` actually returns the error from the gorm `Create` method.

**Pull request closed without merging**
