### PR TITLE
solve issue scope deleted_at

### PR DESCRIPTION
**Pull request by xamu**

### CODE REVIEW

**Comment by rolies106** [comment]
+1 Need this one

**Comment by arifwiwoho2** [comment]
+1 idem

**Comment by zardak** [comment]
Aren't you misusing the `DeletedAt` field? It's supposed to be of `*time.Time` type.

What's the purpose of this change?

**Comment by xamu** [comment]
While i use Save function to update a record, its also changes the value of DeletedAt field to '0000-00-00 00:00:00' so when i query it using First function the record considered soft deleted by gorm because the condition only get the record when the column value is null.

actually it can be solve by either modify the query scope or the Save function to not touch deleted_at field.

**Comment by jiulongw** [comment]
@xamu This happens when you use `time.Time` type for DeletedAt.  As @zardak mentioned it should be `*time.Time` type instead.

**Comment by jinzhu** [comment]
If using *time.Time, its value should be NULL.

**Comment by xamu** [comment]
Yup it works with *time.Time type.

It was my own mistake, thanks a lot guys.

**Pull request closed without merging**
