### PR TITLE
Add RollbackUnlessCommitted()

### PR DESCRIPTION
**Pull request by AdamSLevy**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested

For significant changes like big bug fixes, new features, please open an issue to make an agreement on an implementation design/plan first before starting it.

### What did this pull request do?
This adds a function called `RollbackUnlessCommitted()` which is intended to be `defer`ed at the beginning of a transaction to avoid needing to call Rollback in every error case. `RollbackUnlessCommitted`  calls sql.Tx.Rollback() and ignores `sql.ErrTxDone` errors, indicating that the transaction was already committed.

Below is an example of its intended usage. In the example only exiting the function through the final return will result in a commit. Any other return will result in a rollback. 

```golang
func doTransaction(DB *gorm.DB) error {
        tx := DB.Begin()
        defer tx.RollbackUnlessCommitted()

        u := User{Name: "test"}
        if err != tx.Save(&User).Error; err != nil {
                return err
        }
        return tx.Commit().Error
}
```

### CODE REVIEW

**Comment by rubensayshi** [comment]
@jinzhu this seems like a no brainer to merge and would be very welcome to see in the next release :)

**Comment by hewenyang** [comment]
The function name seems a bit long. I believe it would suffice to make Rollback a no-op when Commit() has been successful, like [Badger](https://godoc.org/github.com/dgraph-io/badger#Txn.Discard) does.

**Comment by pwli0755** [comment]
What's the difference between `defer tx.RollbackUnlessCommitted()` and `defer tx.Rollback()`?

**Comment by rubensayshi** [comment]
`defer tx.Rollback()` will log an error if you called `tx.Commit()` anywhere before the defer occurs.  
it doesn't panic but just does a `log.Error` so it was never harmful, but it was anoying and look worrying for many devs. 

but other than the log line the `defer tx.Rollback()` won't have any effect if you did `tx.Commit()` before the defer occurs.

**Pull request merged**
