### PR TITLE
i think it's better,please think about it

### PR DESCRIPTION
**Pull request by liu-xuewen**
Make sure these boxes checked before submitting your pull request.

- [] Do only one thing
- [] No API-breaking changes
- [] New code/logic commented & tested
- [] Write good commit message, try to squash your commits into a single one
- [] Run `./build.sh` in `gh-pages` branch for document changes

For significant changes like big bug fixes, new features, please open an issue to make a agreement on an implementation design/plan first before starting it.

Thank you.

### CODE REVIEW

**Comment by liu-xuewen** [comment]
The sql print  missing return result,can i add it ?thanks very much!

**Comment by jinzhu** [comment]
Thank you for your PR.

**Comment by andreynering** [comment]
Nice feature! But maybe red is not the right color for it? Red is the color that currently print errors. Maybe change to another one?

**Pull request merged**
