### PR TITLE
Wercker postgres and mysql

### PR DESCRIPTION
**Pull request by nkovacs**
I've set up a wercker.yml to run automated tests on mysql and postgres in addition to sqlite: https://app.wercker.com/#nkovacs/gorm/build/5740cb2c137f7fe21f0bf338
I can squash the commits if you'd like.

### CODE REVIEW

**Comment by nkovacs** [comment]
I think you'll need to migrate to the docker-based wercker stack for this to work: http://devcenter.wercker.com/docs/faq/migration-tips-v2.html

**Comment by jinzhu** [comment]
Hi @nkovacs 

Thank you for this, looks good.

Could you squash the commit before merge it?

**Comment by jinzhu** [comment]
btw, you might noticed this error, anything I need to setup for the wercker?

https://app.wercker.com/#buildstep/5740ccf6137f7fe21f0bf424

image

**Comment by nkovacs** [comment]
I'm not sure what's happening, because with my fork, everything is working fine, so it's probably a different configuration in wercker. My guess is you are using an older wercker config (http://devcenter.wercker.com/docs/faq/migration-tips-v2.html), but I can't set my fork to use the old infrastructure, and I can't find the infrastructure option mentioned in the migration guide either.

**Pull request merged**
