### PR TITLE
Added redshift support & added Dialect.SupportLastInsertID interface method

### PR DESCRIPTION
**Pull request by gnagel**
### What
- Added a new "redshift" dialect
- Added interface method `Dialect.SupportLastInsertID`, redshift does not support `LastInsertId`
- Updated create_callback to check if the dialect supports LastInsertId: `scope.Dialect().SupportLastInsertID()`
### Why
- Redshift is very useful large scale data storage, but the create table syntax is not compatible with Postgresql
- Only a subset of data types are supported
- Redshift doesn't support _LastInsertId_ so we need to check for that when inserting new records.
### Example usage

``` go
package main

import (
    "os"
    "fmt"
    "github.com/jinzhu/gorm"
    _ "github.com/jinzhu/gorm/dialects/redshift"
)


type Product struct {
    ID uint `gorm:"DISTKEY IDENTITY(1, 1)"`
    Code string
    Price uint
}

func main() {
    // Get the database connection from the environment
    // Ex: 
    //   db_connection_string := "postgres://root:password@products.crtfrkqszbch.us-east-1.redshift.amazonaws.com:5439/products?sslmode=verify-ca&sslrootcert=./redshift-ssl-ca-cert.pem"
    // 
    // The redshift PEM is stored here:  https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html#connect-using-ssl
    // 
    db_connection_string := os.Getenv("DB_CONNECTION")
    db, err := gorm.Open("redshift", "postgres", db_connection_string)
    if err != nil {
        panic("failed to connect database: " + db_connection_string + "\n" + err.Error())
    }
    defer db.Close()
    // db.LogMode(true)

    db.DropTable(&Product{})

    // Migrate the schema
    db.AutoMigrate(&Product{})

    // Create
    db.Create(&Product{Code: "L1212", Price: 1000})

    // Read
    var product Product
    db.First(&product, 1) // find product with id 1
    db.First(&product, "code = ?", "L1212") // find product with code l1212

    // Update - update product's price to 2000
    db.Model(&product).Update("Price", 2000)

    // Delete - delete product
    db.Delete(&product)
}
```

### CODE REVIEW

**Comment by gnagel** [comment]
Hi @jinzhu!
Please merge this pr into gorm!

Thanks,
Glenn

**Comment by gnagel** [comment]
Closing this PR out

**Comment by iain17** [comment]
Why was this not merged? This is exactly what I need aswell.

**Comment by iain17** [comment]
@gnagel Found an issue with the redshift implementation. When it creates a table it throws an error when it creates the indexes:

```
(pq: SQL command "CREATE INDEX idx_example_deleted_at ON "example"(deleted_at) " not supported on Redshift tables.)

**Pull request closed without merging**
