### PR TITLE
Add RollbackUnlessCommitted

### PR DESCRIPTION
**Pull request by DoubleDi**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested

For significant changes like big bug fixes, new features, please open an issue to make an agreement on an implementation design/plan first before starting it.

### What did this pull request do?
Hi @jinzhu ! Awesome refactoring with v2 going on.
Added RollbackUnlessCommitted func for transactions. Helps not to write a lot of rollback code on error checking!

Example
```
tx := db.Begin()
defer tx.RollbackUnlessCommitted()
if somerrhappened {
     // no need for rollback here
     return
}
if othererrhappened {
     // no need for rollback here
     return
}
tx.Commit()
```

also please keep in mind that you should write commiTTer with double T.

### CODE REVIEW

**Comment by jinzhu** [comment]
Hello,

Thank you for your PR.

It won't work after adding the `RollbackUnlessCommitted` method to `TxCommiter ` as `database/sql` doesn't implement this method.

And I would suggest we don't add API like this but just using method `Transaction` like this  http://gorm.io/docs/transactions.html#Transactions

Could you open another PR to fix the typo, thank you ;)

**Comment by DoubleDi** [comment]
Yes, didn't think of that. 
I reviewed the changes and we actually don't  need `RollbackUnlessCommitted` in  `TxCommitter`, only need it in `DB`. So maybe this PR is still considerable? 
Or maybe we can use you callbacks and put beside `CommitOrRollback`?

**Comment by jinzhu** [comment]
Have you checked out the `Transaction` method? I prefer to use it than adding a new API.

**Comment by DoubleDi** [comment]
Ok it's pretty handy too. Thanks

**Pull request closed without merging**
