### PR TITLE
`CurrentDatabase' implementation.

### PR DESCRIPTION
**Pull request by jaytaylor**
I've found this functionality to be very useful in my own projects to avoid hardcoding database names.

I took the time to add support for all dialects and add a corresponding unit-test.

### CODE REVIEW

**Comment by jaytaylor** [comment]
I just noticed that there is a pre-existing databaseName() function that attempts to infer the name from the connection string.  I plan to see clean that up in this PR.

**Comment by jaytaylor** [comment]
I believe this is now ready to be reviewed!

**Comment by jinzhu** [comment]
Hi @jaytaylor

Thank you for your PR as always.

But why not just return the database name as string? It sounds easier for users to use it?

**Comment by jaytaylor** [comment]
I started out with that, but when using it, it felt unnatural to not return *DB like the rest of the gorm API.  So I changed it to be more like gorm-style: `gorm.First(&model)`.

**Comment by jinzhu** [comment]
I think that's fine to return the database name as string. it would be easier for others to use it?

**Comment by jaytaylor** [comment]
I agree that either implementation will work, happy to change it to the way you like.

**Comment by jaytaylor** [comment]
@jinzhu Requested changes implemented and merged into PR #606 as well!

**Pull request merged**
