### PR TITLE
Implementing crate dialect

### PR DESCRIPTION
**Pull request by aanm**
I believe this is only a small amount of work for crate to be implemented on this ORM. But for now those were the only workarounds that I've found so crate would work.

Feel free to discuss anything.
The crate that I'm talking about is https://crate.io/
Signed-off-by: André Martins <martins@noironetworks.com>

### CODE REVIEW

**Comment by jaytaylor** [comment]
Hey @aanm,

Thanks for this, I hadn't seen crate before.  It looks interesting!

And.. how about some unit-test integration for crate (like is available for all the other supported backends)?

**Comment by aanm** [comment]
@jaytaylor Are you talking about this https://github.com/jinzhu/gorm/blob/master/main_test.go

**Comment by jaytaylor** [comment]
@aanm yep, that kind of stuff is what I'm referring to.

**Comment by aanm** [comment]
@jaytaylor Sorry, it turns out we are not going to pursuing this since it is not exactly what we need. You can close this PR or leave it open if anyone want to continue want it is missing.

**Comment by jaytaylor** [comment]
@aanm thanks for following up!  I am curious about what you guys are pursuing instead, can you share?

**Comment by jinzhu** [comment]
I am going to close this one, seems like I am not a big fan of this database.

I  will open an API in the future, so you could implement dialects for other databases w/o modify gorm's source code.

**Pull request closed without merging**
