### PR TITLE
Second part of the defaultTableName field race fix

### PR DESCRIPTION
**Pull request by mtfelian**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested

For significant changes like big bug fixes, new features, please open an issue to make an agreement on an implementation design/plan first before starting it.

### What did this pull request do?

Second part of #1407 fix as @dnathe4th reported

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @mtfelian 

Could you point out where the data race could happen? seems like the lock is not necessary.

**Comment by dnathe4th** [comment]
The read is on line 32 and the write is on 35 for line numbers before
mtfelian's proposed change. There is no concurrency access protection to
the defaultTableName field without a change like this PR.

**Comment by jinzhu** [comment]
Hi @dnathe4th @mtfelian 

Could you provide a script that could reproduce this issue? I am using `go test --race` can't reproduce it.

**Comment by dnathe4th** [comment]
```bash
[] dnathe4th@~/gopath/src/dnathe4th/gorm-test: cat main.go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Model struct {
	gorm.Model
	Name string
}

func main() {
	db, err := gorm.Open("sqlite3", "test.db")
	if err != nil {
		panic("failed to connect database")
	}
	defer db.Close()

	c := make(chan struct{}, 10)
	for i := 0; i < 10; i++ {
		go func(n int) {
			var ms []*Model
			db.Where("name = ?", "doesnotexist").Find(&ms)
			c <- struct{}{}
		}(i)
	}

	for i := 0; i < 10; i++ {
		<-c
	}
}
[] dnathe4th@~/gopath/src/dnathe4th/gorm-test: go run -race main.go
==================
WARNING: DATA RACE
Write at 0x00c420234090 by goroutine 15:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Previous write at 0x00c420234090 by goroutine 16:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Goroutine 15 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126

Goroutine 16 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126
==================
==================
WARNING: DATA RACE
Write at 0x00c420234090 by goroutine 11:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Previous write at 0x00c420234090 by goroutine 16:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Goroutine 11 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126

Goroutine 16 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126
==================
==================
WARNING: DATA RACE
Read at 0x00c420234090 by goroutine 9:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:53 +0x45
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).whereSQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:711 +0x53
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).CombinedConditionSql()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:345 +0x7b
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0x103
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Previous write at 0x00c420234090 by goroutine 16:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Goroutine 9 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126

Goroutine 16 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126
==================
==================
WARNING: DATA RACE
Write at 0x00c420234090 by goroutine 12:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Previous write at 0x00c420234090 by goroutine 16:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Goroutine 12 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126

Goroutine 16 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126
==================
==================
WARNING: DATA RACE
Read at 0x00c420234090 by goroutine 8:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:53 +0x45
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).whereSQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:711 +0x53
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).CombinedConditionSql()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:345 +0x7b
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0x103
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Previous write at 0x00c420234090 by goroutine 16:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Goroutine 8 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126

Goroutine 16 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126
==================
==================
WARNING: DATA RACE
Read at 0x00c420234090 by goroutine 10:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:53 +0x45
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).whereSQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:711 +0x53
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).CombinedConditionSql()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:345 +0x7b
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0x103
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Previous write at 0x00c420234090 by goroutine 16:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Goroutine 10 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126

Goroutine 16 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126
==================
==================
WARNING: DATA RACE
Write at 0x00c420234090 by goroutine 17:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Previous write at 0x00c420234090 by goroutine 16:
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2ad
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).TableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:327 +0x1b5
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).prepareQuerySQL()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:843 +0xde
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.queryCallback()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/callback_query.go:54 +0x2e1
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90
  dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm.(*DB).Find()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/vendor/github.com/jinzhu/gorm/main.go:309 +0xfe
  main.main.func1()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:24 +0x12c

Goroutine 17 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126

Goroutine 16 (running) created at:
  main.main()
      /Users/dnathe4th/gopath/src/dnathe4th/gorm-test/main.go:22 +0x126
==================
Found 7 data race(s)
exit status 66
```

**Comment by desdic** [comment]
I still get a race condition in 

WARNING: DATA RACE                                                                                                                                                                                                  
Write at 0x00c0001858f0 by goroutine 13:                                                                                                                                             
  djc/vendor/github.com/jinzhu/gorm.(*ModelStruct).TableName()                                                                                                                                                      
      /home/kgn/src/biq/dow-jones-compliance/src/djc/vendor/github.com/jinzhu/gorm/model_struct.go:62 +0x2d3
  djc/vendor/github.com/jinzhu/gorm.(*Scope).TableName()                                                                                                                                                            
      /home/kgn/src/biq/dow-jones-compliance/src/djc/vendor/github.com/jinzhu/gorm/scope.go:327 +0x207                                                                                                              
  djc/vendor/github.com/jinzhu/gorm.(*Scope).QuotedTableName()                                                                                                                                                      
      /home/kgn/src/biq/dow-jones-compliance/src/djc/vendor/github.com/jinzhu/gorm/scope.go:339 +0x52                                                                                                               
  djc/vendor/github.com/jinzhu/gorm.queryCallback()                                                                                                                                                                 
      /home/kgn/src/biq/dow-jones-compliance/src/djc/vendor/github.com/jinzhu/gorm/callback_query.go:32 +0xfcd                                                                                                      
  djc/vendor/github.com/jinzhu/gorm.(*Scope).callCallbacks()                                                                                                                                                        
      /home/kgn/src/biq/dow-jones-compliance/src/djc/vendor/github.com/jinzhu/gorm/scope.go:857 +0x90                                                
  djc/vendor/github.com/jinzhu/gorm.(*DB).First()                                                                                                                                                                   
      /home/kgn/src/biq/dow-jones-compliance/src/djc/vendor/github.com/jinzhu/gorm/main.go:289 +0x215                    

when using v1.9.1 and using go 1.11 .. will there be a new version with this fix ?

**Comment by dnathe4th** [comment]
Hey @desdic can you post this as a new issue? Also please make sure to include the full stack trace. What you pasted there only has the `Write at` stack, not the other part of the race (probably a `Read at`)

**Comment by desdic** [comment]
Sure I'll create a new issue on it

**Pull request merged**
