### PR TITLE
Postgres driver updated for FoundationDB auto-migration compatibility.

### PR DESCRIPTION
**Pull request by jaytaylor**
$ ./test_all.sh
    testing postgres...
    [info] replacing callback `create` from callback_test.go:94
    [info] removing callback `create` from callback_test.go:107
    `testdb` is not officially supported, running under compatibility mode.
    PASS
    ok  	gorm	1.364s

### CODE REVIEW

**Comment by jinzhu** [comment]
Hello @jaytaylor 

Do you think hack postgres dialect to support foundation db is good? or have a foundation dialect maybe better?

**Comment by jaytaylor** [comment]
Hey @jinzhu,

I think this is a good option for us to consider and discuss.

Pros of bundling them together:

* Foundation is already highly compatible with all things postgres, in fact the only driver issue I've run into is this one - where pg_* tables are being referenced and queried.
* Less duplicated code to maintain.

Cons:

* Supporting both in one driver complicates the PG driver.

My proposal is to merge this compatibility PR for now, and re-evaluate if/when additional compatibility issues arise.  In my opinion the optimal path is to start with a simple approach that works and then spend the effort to refactor FDB into it's own driver when we are confident it's warranted.

Believe me, I know Gorm is great and I really like this project!  I don't want to see any of it get ugly.  At the same time I want to ensure we keep it maximally useful and avoid prematurely introducing  complexity in the form of ~95% duplicated drivers.

What are your thoughts?

**Comment by jinzhu** [comment]
Ok, lets do this, but seems like this will broken pg test in my machine

selection_477

```go
+ // Determine whehter the pg_indexes talbe is
+ detect := []int{} //make([]int, 2) // If detect[0] == 1 then we have postgres, else if detect[1] == 1 then we have detectationDB.
+ scope.NewDB().Raw(`SELECT count(*) "detect" FROM INFORMATION_SCHEMA.tables WHERE table_name = 'pg_indexes' UNION SELECT count(*) "detect" FROM INFORMATION_SCHEMA.tables WHERE table_name = 'indexes'`).Pluck("detect", &detect)

Seems like we can't use detect[0] == 1, detect[1] == 1 to detect it is pg or fdb
```

**Comment by jaytaylor** [comment]
Nice catch, I will fix this up.

**Comment by jaytaylor** [comment]
@jinzhu This should now be cleaned up and ready, I've tested thoroughly on both postgres and  foundation.

=== RUN TestAutoMigration
--- PASS: TestAutoMigration (0.01s)

**Comment by jaytaylor** [comment]
Actually hang on, I am seeing issues with this.

**Comment by jaytaylor** [comment]
I've added an additional improvement in the Pluck error messaging.

**Comment by jinzhu** [comment]
Hello @jaytaylor 

Did you noticed my latest change about the dialect? the postgres dialect embedded a common dialect, so I am thinking, maybe we could add a foundationdb dialect, and embed the postgres dialect, then just overwrite those methods behavioured differently?

**Comment by jaytaylor** [comment]
Sure, that sounds reasonable to me!

**Comment by jaytaylor** [comment]
@jinzhu I'm closing this PR in favor of a new one for the full FoundationDB driver.

Cheers,
Jay

**Pull request closed without merging**
