### PR TITLE
[WIP] Add Oracle support

### PR DESCRIPTION
**Pull request by andreynering**
Rebased but having problems. Not done to merge.

### CODE REVIEW

**Comment by andreynering** [comment]
Can now run tests with:

```bash
GORM_DIALECT=oci8 go test -v -tags oci8
```

Currently failing with the following output: https://gist.github.com/andreynering/ae4caef4edf7d58f2711f954c82ef102

**Comment by agamdua** [comment]
Hey! I'd love to use this, and contribute to it if you need any help. Are there any specific things that are left to do? If you could share that I'd be happy to pitch in.

**Comment by andreynering** [comment]
@agamdua

I haven't touched this in 4 months.

Some things were working, AutoMigrate, queries, etc.

But there was some problems. Those I can remember are: limit and offset, I don't know how to make auto increment with (need to fetch sequence value first to then insert), Oracle has length limit for constraints and indexes names, lots of failing tests, others I can't remember...

Anyone that want is free to continue my work, just fetch the branch on my fork.

**Comment by hoop33** [comment]
@agamdua Are you working on this? Need help? Not sure how surmountable the issues are, but would love to use gorm with Oracle.

**Comment by giorgiootto** [comment]
Anybody is developing a dialect oracle?????

**Comment by andreynering** [comment]
@giorgiootto No, nobody. Oracle is harder to support than other databases, so I don't know if that will ever happen.

But if anyone is willing to work on this, feel free to hack with the `oracle` branch on my fork.

You can take a look at [Xorm](https://github.com/go-xorm/xorm) that seems to support it (I haven't tried myself), or use raw SQL.

**Comment by AmanPatelcubastion** [comment]
@agamdua , query and delete works fine but things like **insert , update , preload** still dont work other than that auto increment dosen't work . Suggest some way to use use them in oracle using gorm ?

**Comment by misterEggroll** [comment]
I've [forked gorm](https://github.com/misterEggroll/gorm) and built a dialect for oracle into it. 
I might have broken the dialect for mysql. However, postgres and oracle definitely work. Issues with limit and offset have been resolved. Inserts and updates also seem to be working.

I haven't explicitly checked preload, however, I think it works. This is based on the fork created by @andreynering. We are currently using my fork to work with both oracle and postgres. If anyone is still looking for this, please feel free to contribute/raise issues for the same.

**Comment by giorgiootto** [comment]
Good news. It´s great.

**Comment by DblK** [comment]
@misterEggroll any chance to have an ETA of the PR here?

**Comment by cjbj** [comment]
@misterEggroll any chance you can use [goracle](https://github.com/go-goracle/goracle/) instead of go-oci8 in your fork?

**Comment by misterEggroll** [comment]
@cjbj You could try it yourself TBH. There's only one place where I specifically use go-oci8. When I try to resolve the ID of the record by making use of the oracle rowID.

I could help you out if you're looking to do that.

**Pull request closed without merging**
