### PR TITLE
Fixed SQL injections with ORDER BY and GROUP BY.

### PR DESCRIPTION
**Pull request by RichardKnop**
This PR is a quick way to solve two found SQL injections.

More tests should be written to test for other possible injections ASAP.

This was discovered by @eazynow. Thank you for spotting this!

### CODE REVIEW

**Comment by RichardKnop** [comment]
@jinzhu

**Comment by RichardKnop** [comment]
Alright this doesn't work. Looking at other ways to fix this.

**Comment by RichardKnop** [comment]
@jinzhu Fixed tests. Now passing.

**Comment by RichardKnop** [comment]
Discovered by @eazynow

**Comment by jinzhu** [comment]
Hi @RichardKnop 

Thank you for your PR. but `Order`, `Group` can't do it like this, as it is supposed to be possible using with sql expression.

I think for your application, it is better to doesn't accept user's input as argument for those two methods, when use those inputs, you have to verify it.

**Pull request closed without merging**
