### PR TITLE
mysql column comment in create table or add column

### PR DESCRIPTION
**Pull request by mzmuer**
Make sure these boxes checked before submitting your pull request.

- [x] Do only one thing
- [x] No API-breaking changes
- [x] New code/logic commented & tested

For significant changes like big bug fixes, new features, please open an issue to make an agreement on an implementation design/plan first before starting it.

### What did this pull request do?
add mysql column comment in create table or add column

usage:  
```
type T struct{
    comment  string  `gorm:"not null;COMMENT:'is comment'"`
}
```

### CODE REVIEW

**Comment by zaneli** [comment]
I think this PR is not necessary because `COMMENT` tag is already works.

https://github.com/jinzhu/gorm/blob/7bc35615034c1d6994088c2cc925086fba6f565e/dialect.go#L129-L131

```go
type T struct {
	Comment string `gorm:"not null;COMMENT:'is comment'"`
}

db.CreateTable(&T{})
```

```sql
CREATE TABLE `ts` (`comment` varchar(255) NOT NULL  COMMENT 'is comment' )
```

```sql
mysql> show create table ts;
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                  |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| ts    | CREATE TABLE `ts` (
  `comment` varchar(255) NOT NULL COMMENT 'is comment'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

**Comment by mzmuer** [comment]
@zaneli okay, I'm using version v1.9.2。I will close this PR. tks。

**Comment by Turing-Chu** [comment]
then how can I add table comment when declare a model?

**Comment by mzmuer** [comment]
> then how can I add table comment when declare a model?

@Turing-Chu The 
`type T struct{
    comment  string  `gorm:"not null; comment:'your comment'"`
}`

the above answers are described

**Comment by Turing-Chu** [comment]
@mzmuer thank you your answer. I have used last night.  the current problem is how can I add table comment?

**Comment by mzmuer** [comment]
@Turing-Chu  
```
type T struct {   
	Field string `gorm:"not null`
}

db.Set("gorm:table_options", "ENGINE=InnoDB comment='your table comment'").CreateTable(&T{})
````

**Comment by Turing-Chu** [comment]
tks @mzmuer

**Pull request closed without merging**
