### PR TITLE
Allows foreign keys to be saved without saving the assoication when s…

### PR DESCRIPTION
**Pull request by joe-at-startupmedia**
…pecified #1628

### What did this pull request do?

Allow foreign keys to be saved when `save_assocations` is false.

### CODE REVIEW

**Comment by jinzhu** [comment]
Hi @joe-at-startupmedia 

Could you make sure code are formatted with gofmt and add a test case for this?

**Comment by joe-at-startupmedia** [comment]
Do you have any docs on getting the tests working? When I run `test_all.sh` I fail with database connection errors.

**Comment by ezk84** [comment]
I have added some tests for this feature after figuring them out, I, unfortunately, could only create a new PR with the additional commit (or is there a way to add the commits here?). 

In any case, reading the main_test.go file I learned we need to create a `gorm` database and set some env variables to be able to run the tests.

**Comment by joe-at-startupmedia** [comment]
@ezk84 Thanks for the tests. I was able to resolve my errors by using the sqlite connector. @jinzhu is this sufficient code coverage for the changes are you expecting something else?

**Comment by jinzhu** [comment]
Hello @ezk84 

Why could I find your tests for this PR?

**Comment by joe-at-startupmedia** [comment]
@jinzhu 
https://github.com/jinzhu/gorm/pull/1664/commits/c82c9b224f7ec9ac3e6d876992d4222348f9a3ee

**Comment by jinzhu** [comment]
Hi @joe-at-startupmedia 

Thank you for your work, have merged this PR, and make it more advanced.

Like you could disable updating associations have a primary key, and keep the ability to create new values.

More details please refer: http://gorm.io/crud.html#associations

Thank you.

**Pull request closed without merging**
